# Generated by Django 4.1.7 on 2023-02-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labuser',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
