# Generated by Django 4.1.7 on 2023-02-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_users', '0003_labuser_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='card_id',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
